axonivy/ui-components

packages/components/package.json
packages/icons/package.json

Fix package json

---

packages/jsonrpc/src/base-rpc-client.ts
packages/jsonrpc/src/connection-util.ts
packages/jsonrpc/src/index.ts
packages/jsonrpc/src/re-exports.ts

- Fix typo in BaseRpcClient
- Rename MessageConnection interface

Reexport vscode-jsonrpc stuff

---

packages/components/src/components/common/table/edit/edit.stories.tsx
packages/components/src/components/common/table/edit/edit.tsx
packages/components/src/components/common/table/row/row.stories.tsx

- Change table updateData to row id

XIVY-13510 Adapt UI changes

---

packages/components/src/components/common/checkbox/checkbox.css.ts
packages/components/src/components/common/combobox/combobox.stories.tsx
packages/components/src/components/common/fieldset/fieldset.css.ts
packages/components/src/components/common/fieldset/fieldset.tsx
packages/components/src/components/common/input/input.css.ts
packages/components/src/components/common/radio/radio.css.ts
packages/components/src/components/common/select/select.css.ts
packages/components/src/components/common/select/select.stories.tsx
packages/components/src/components/common/textarea/textarea.css.ts
packages/components/src/components/common/textarea/textarea.stories.tsx
packages/components/src/styles/disabled.ts
packages/components/src/styles/theme.css.ts

- Update disabled styles
- Inputs in fieldset with message get color border

XIVY-13510 Adapt Ui

---

packages/components/src/components/common/table/edit/edit.tsx
packages/components/src/components/detail/header/header.css.ts

XIVY-13510 Export edit cell hook

---

packages/components/src/components/common/table/edit/edit.stories.tsx
packages/components/src/components/common/table/tree/data.ts
packages/components/src/components/common/table/tree/tree.stories.tsx
packages/components/src/components/common/table/tree/tree.tsx

- Support custom value
- Support lazy loading

Improve tree

---

packages/components/src/components/common/input/input.test.tsx
packages/components/src/components/common/input/input.tsx
packages/components/src/components/common/radio/radio.test.tsx
packages/components/src/context/useReadonly.test.tsx
packages/components/src/context/useTheme.test.tsx
packages/components/src/context/useTheme.tsx

Same as on master: https://github.com/axonivy/ui-components/pull/74

 XIVY-14079 Fix theme without localstorage usage #74  > R11.3

---

packages/components/src/components/common/index.ts
packages/components/src/components/common/skeleton/skeleton.css.ts
packages/components/src/components/common/skeleton/skeleton.stories.tsx
packages/components/src/components/common/skeleton/skeleton.tsx

also maybe to show loading stuff?
https://jenkins.ivyteam.io/job/ui-components/job/add-skeleton-component/4/artifact/packages/components/storybook-static/index.html?path=/story/common-skeleton--default

Add skeleton component

---

packages/components/src/components/common/index.ts
packages/components/src/components/common/spinner/spinner.css.ts
packages/components/src/components/common/spinner/spinner.stories.tsx
packages/components/src/components/common/spinner/spinner.tsx

https://jenkins.ivyteam.io/job/ui-components/job/add-spinner-component/3/artifact/packages/components/storybook-static/index.html?path=/story/common-spinner--default
with second small size.
for show loading states

Add spinner component

---

package-lock.json
packages/components/package.json
packages/components/src/components/common/index.ts
packages/components/src/components/common/toaster/toaster.css.ts
packages/components/src/components/common/toaster/toaster.stories.tsx
packages/components/src/components/common/toaster/toaster.tsx

https://jenkins.ivyteam.io/job/ui-components/job/add-toaster-component/1/artifact/packages/components/storybook-static/index.html?path=/story/common-toaster--default
idea: for neo when requests fail to show a message

Add toaster component

---

package-lock.json
package.json
packages/components/package.json
packages/components/src/components/common/button/button.stories.tsx
packages/components/src/components/common/dialog/dialog.css.ts
packages/components/src/components/common/dialog/dialog.stories.tsx
packages/components/src/components/common/dialog/dialog.tsx
packages/components/src/components/common/flex/flex.css.ts
packages/components/src/components/common/index.ts
packages/components/src/components/detail/header/header.stories.tsx

the base for a browser component, but a dialog is needed anyways
FYI @ivy-fhe

Add dialog component

---

packages/components/src/components/common/dialog/dialog.css.ts
packages/components/src/components/common/dialog/dialog.stories.tsx

- Portal should handle that the dialog is on top (otherwise set z-index manual)

Remove z-index form default dialog styles

---

package-lock.json
packages/components/package.json
packages/components/src/components/common/index.ts
packages/components/src/components/common/toggleGroup/toggleGroup.css.ts
packages/components/src/components/common/toggleGroup/toggleGroup.stories.tsx
packages/components/src/components/common/toggleGroup/toggleGroup.tsx

My first component for the UI components. I would then like to use the ToggleBar in the form editor. Feedback?
I wasn't quite sure whether I should implement the ToggleBarItemOnlyIcon component as I did or simply work with the ToggleBarItem component and filter out this scenario with if-statements. What do you think?

XIVY-13261 Add ToggleBar Component

---

packages/components/src/components/common/switch/switch.css.ts
packages/components/src/components/common/switch/switch.stories.tsx
packages/components/src/components/common/switch/switch.tsx

https://github.com/axonivy/ui-components/pull/112

XIVY-13261 Add Icon to Switch-Component

---

packages/components/src/components/common/toggleGroup/toggleGroup.css.ts

I realised during the integration into the form editor that I have to remove this padding, sorry

XIVY-13261 Remove Padding from toggleGroup

---

packages/components/src/components/editor/browser/browser.tsx

I wrongly used undefined instead of unknown. 
Sorry.

XIVY-14263 replace wrong undefined with unknown

---

packages/components/src/components/editor/browser/browser.stories.tsx

Add browser with title example

---

packages/components/src/components/editor/sidebar/emptyDetail/emptyDetail.css.ts
packages/components/src/components/editor/sidebar/emptyDetail/emptyDetail.stories.tsx
packages/components/src/components/editor/sidebar/emptyDetail/emptyDetail.tsx

I had to improve the emptyDetail component and add the ability to customise flex-direction and access the basic HTMLDivElement props.

XIVY-13261 Improve emptyDetail component

---

packages/components/src/components/editor/browser/browser.css.ts
packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.tsx
packages/components/src/components/editor/browser/data.ts

- Overflow description
- Custom apply button label and icon

XIVY-14263 Improve browser

---

packages/components/src/components/common/table/header/header.stories.tsx
packages/components/src/components/common/table/header/header.test.tsx
packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.test.tsx
packages/components/src/components/editor/browser/browser.tsx
packages/components/src/components/editor/sidebar/header/header.stories.tsx
packages/components/src/components/editor/sidebar/header/header.test.tsx

- No result message (can be adjusted if wished)
- Init search input (e.g. current value of input)
- Add tests for browser

Improve browser

---

packages/components/src/components/common/checkbox/checkbox.stories.tsx
packages/components/src/components/common/collapsible/collapsible.stories.tsx
packages/components/src/components/common/switch/switch.css.ts
packages/components/src/components/common/table/row/row.css.ts
packages/components/src/components/common/table/tree/tree.css.ts
packages/components/src/components/common/table/tree/tree.tsx
packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/editor.stories.tsx
packages/components/src/components/editor/sidebar/header/header.stories.tsx
packages/components/src/components/editor/sidebar/outline/data.ts
packages/components/src/components/editor/sidebar/outline/outline.css.ts
packages/components/src/components/editor/sidebar/outline/outline.stories.tsx
packages/components/src/components/editor/sidebar/outline/outline.test.tsx
packages/components/src/components/editor/sidebar/outline/outline.tsx
packages/components/src/components/editor/sidebar/sidebar.stories.tsx
packages/components/src/index.ts

Example usage form editor: https://github.com/axonivy/form-editor-client/pull/117

Create outline component

---

package-lock.json
packages/jsonrpc/package.json
packages/jsonrpc/src/base-rpc-client.ts
packages/jsonrpc/src/connection-util.test.ts
packages/jsonrpc/src/connection-util.ts
packages/jsonrpc/src/disposable.ts
packages/jsonrpc/src/index.ts
packages/jsonrpc/src/vscode-jsonrpc-reexports.ts
packages/jsonrpc/src/ws-connection-provider.test.ts
packages/jsonrpc/src/ws-connection-provider.ts

- Remove dependency to vscode-ws-jsonrpc
- Add tests for connection util
- Cleanup old code

XIVY-14729 Cleanup jsonrpc code

---

.vscode/launch.json
build/Jenkinsfile
package-lock.json
packages/components/package.json
packages/components/vite.config.ts

- Do not inline sourcemap to components.js (increase the sice of it ca 5 times)
- Fix debug by set webRoot to the launch config
- Do not run storybook build locally

Fix sourcemap

---

packages/components/src/components/common/collapsible/collapsible.stories.tsx
packages/components/src/components/common/collapsible/collapsible.test.tsx
packages/components/src/components/common/collapsible/collapsible.tsx
packages/components/src/components/common/state/state.tsx

Basic select that supports to have message, controls and change it's open state if the `open` prop changes or has default open if there are messages

Add BasicCollapsible

---

packages/components/src/components/common/accordion/accordion.css.ts
packages/components/src/components/common/accordion/accordion.stories.tsx
packages/components/src/components/common/accordion/accordion.tsx
packages/components/src/components/common/accordion/useSticky.ts

- With messages and control how we use it currently
- With sticky mode

Add BasicAccordionItem

---

packages/components/src/components/common/table/row/row.css.ts

Fix dnd line if move down

---

packages/components/src/utils/useShortcut.test.tsx
packages/components/src/utils/useShortcut.ts

Return a string representation of the shortcut to be used for tooltips and such.

XIVY-15138 return shortcut string

---

packages/components/src/components/common/combobox/combobox.tsx
packages/components/src/components/common/dialog/dialog.stories.tsx

Otherwise it will trigger if enter is pressed in a from

Fix combobox button should not be type submit

---

packages/components/src/components/common/table/hooks/hooks.test.tsx
packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/row/row.stories.tsx
packages/components/src/components/common/table/row/row.test.tsx
packages/components/src/utils/table/table-data.test.ts
packages/components/src/utils/table/table.test.ts
packages/components/src/utils/table/table.ts
packages/components/src/utils/table/test-utils/setup.ts

Demo (Table --> Row --> Multi Select With Reorder): https://jenkins.ivyteam.io/job/ui-components/job/add-shift-multiselect/5/artifact/packages/components/storybook-static/index.html?path=/story/common-table-row--multi-select-with-reorder

XIVY-15138 Add Multiselect with Shift and Ctrl+Shift for Table

---

packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.tsx

Now I can add for example a ... button in the top right corner to enable additional functionality in the browser.

XIVY-15123 Enable placement of a Button in the top right corner of the Browser

---

.gitignore
.ivy/raise-version.sh
build/icons/Dockerfile
build/icons/Jenkinsfile
packages/icons/assembly.xml
packages/icons/pom.xml

Regarding https://github.com/axonivy/doc-images/pull/73

publish icons to maven to be consumend by doc

---

packages/components/src/components/common/table/edit/edit.css.ts
packages/components/src/components/common/table/edit/edit.stories.tsx

Fix style of disabled edit cells

---

packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.tsx
packages/components/src/components/editor/condition-builder/condition-builder-utils.ts
packages/components/src/components/editor/condition-builder/condition.tsx
packages/components/src/components/editor/condition-builder/conditionBuilder.css.ts
packages/components/src/components/editor/condition-builder/conditionBuilder.stories.tsx
packages/components/src/components/editor/condition-builder/conditionBuilder.tsx
packages/components/src/components/editor/condition-builder/conditionBuilderContext.test.ts
packages/components/src/components/editor/condition-builder/conditionBuilderContext.tsx
packages/components/src/components/editor/condition-builder/conditionGroup.tsx
packages/components/src/index.ts

Here is my suggestion for the Condition Builder in UI Components (currently just a draft, as I still want to add tests, but you can take a look at it in the meantime):
In the Browser story, I demonstrate how to integrate the Condition Builder as a browser into the BrowserView, and in the ConditionBuilder story, I show how to use the condition builder independently (so it can already be used in the inscription as well).

XIVY-15533 Add ConditionBuilder

---

packages/components/src/context/useTheme.test.tsx
packages/components/src/context/useTheme.tsx

Use to fix remove theme option in editors which share global theme (e.g. neo)

Add disable flag to theme context

---

packages/components/src/components/common/inputbadge/inputBadge.stories.tsx
packages/components/src/components/common/inputbadge/inputBadge.test.tsx
packages/components/src/components/common/inputbadge/inputBadge.tsx

- changes the badge matching to return early if a badge is found
- order of badgeProp priority is now from high to low

XIVY-15526 badgeInput early return on regex match

---

packages/components/src/components/common/inputbadge/inputBadge.stories.tsx
packages/components/src/components/common/inputbadge/inputBadge.tsx

- Adds an optional tooltip to the inputBadge component
- Adds optional tooltip generator function to BadgeProps
- Tooltip generator function uses original badge text

XIVY-15526 adds optional tooltip to inputBadge

---

dev-packages/eslint-config/base.mjs

- Allow playwright conditional skips
- Ignore vitest.workspace.ts

EsLint rule updates

---

packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/row/row.stories.tsx

Cherry-Pick table keyboard handler for 12

XIVY-13545 Impr. TableKeyHandler to work with structuredClone

---

package-lock.json
packages/components/package.json
packages/components/src/hooks/hotkey.stories.tsx
packages/components/src/hooks/hotkey.test.tsx
packages/components/src/index.ts
packages/components/src/utils/hotkey.test.tsx
packages/components/src/utils/hotkey.ts
packages/components/src/utils/useShortcut.ts

- Deprecate useShortcut hook
- Add react-hotkeys-hook lib
- Add hotkeyText utility function

XIVY-15631 Add react-hotkeys-hook, with hotkey helper text function

---

packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/row/row.stories.tsx
packages/components/src/components/common/table/row/row.test.tsx
packages/components/src/components/editor/browser/browser.tsx

Cherry-Pick from: https://github.com/axonivy/ui-components/pull/224

XIVY-13545 Add onSelect Callbackfunction to TableSelect hook

---

packages/components/src/components/common/checkbox/checkbox.css.ts
packages/components/src/components/common/collapsible/collapsible.css.ts

https://github.com/axonivy/ui-components/pull/226

Improve focus > R12

---

packages/components/src/utils/hotkey.test.tsx
packages/components/src/utils/hotkey.ts

https://github.com/axonivy/ui-components/pull/228

Option key > R12

---

packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/row/row.test.tsx

master: https://github.com/axonivy/ui-components/pull/230

XIVY-13545 Fix table select via arrows

---

packages/components/src/components/common/table/hooks/hooks.tsx

https://github.com/axonivy/ui-components/pull/232

XIVY-15630 Do only stopPropagate table key event if one of listend keys

---

packages/components/src/components/common/resizeable/resizable.tsx
packages/components/src/hooks/hotkey.ts
packages/components/src/index.ts

https://github.com/axonivy/ui-components/pull/236

Reexport react-hotkeys-hook > R12

---

packages/components/src/hooks/hotkey.stories.tsx
packages/components/src/hooks/useHistoryData.stories.tsx
packages/components/src/hooks/useHistoryData.test.ts
packages/components/src/hooks/useHistoryData.ts
packages/components/src/index.ts
packages/components/src/types/lambda.ts
packages/components/tsconfig.json

master: https://github.com/axonivy/ui-components/pull/239

XIVY-15022 Add history data hook > R12

---

packages/components/src/utils/hotkey.test.tsx
packages/components/src/utils/hotkey.ts

https://github.com/axonivy/ui-components/pull/241

Export isMac/isWindows function

---

packages/components/src/utils/hotkey.ts

https://github.com/axonivy/ui-components/pull/243

Undo-redo-fix-12

---

packages/components/src/components/common/combobox/combobox.tsx
packages/components/src/components/common/select/select.tsx
packages/components/src/components/common/table/edit/edit.stories.tsx
packages/components/src/components/common/table/edit/edit.test.tsx
packages/components/src/components/common/table/edit/edit.tsx
packages/components/src/components/common/table/footer/footer.tsx
packages/components/src/components/common/table/table.css.ts

R12 add keyboard support editable tables

---

.github/renovate.json

https://github.com/axonivy/renovate-config/pull/11

Ignore volta handled by base config

---

package-lock.json
packages/icons/package.json

Downgrade fantasicon

---

packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/table.tsx

https://github.com/axonivy/ui-components/pull/376

XIVY-16222 Support table key arrow up/down scroll with virtualized rows

---

packages/components/src/components/editor/condition-builder/condition.tsx
packages/components/src/components/editor/condition-builder/conditionBuilder.css.ts
packages/components/src/components/editor/condition-builder/conditionBuilder.tsx

- specifies for the condition-values to grow, but also shrink below content size

XIVY-16414 condition-builder support for long values

---

packages/components/src/components/common/table/table.css.ts
packages/components/src/components/editor/browser/browser.tsx

- default cursor when hover table
- increase gaps between tabs and content + between info and save

Browser style improvments

---

packages/components/src/components/common/table/table.css.ts
packages/components/src/components/editor/browser/browser.tsx

https://github.com/axonivy/ui-components/pull/420

Browser style improvments > R12

---

packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.test.tsx
packages/components/src/components/editor/browser/browser.tsx

If there's only one browser in a browser view, there's no reason to show the tabs to switch between the different browsers.

XIVY-15944 hide single browser tab

---

packages/components/src/components/common/table/tree/tree.tsx
packages/components/src/components/editor/browser/browser.tsx

With icons:
Without icons:
Mixed (if you're brave enough):

XIVY-15944 make icon optional for browser nodes

---

packages/components/src/index.ts
packages/graph/src/edges/graphEdge.css.ts
packages/graph/src/graph.css.ts
packages/graph/src/graph.tsx
packages/graph/src/nodes/graphNode.css.ts
vite.config.ts

- Reuse color variables
- Colors of nodes, edge labels, etc.
- React flow menus

Fix graph in dark mode

---

packages/components/src/components/common/inputbadge/inputBadge.css.ts
packages/components/src/components/common/inputbadge/inputBadge.tsx

XIVY-16748 Input Badges should not wrap

---

packages/components/src/components/common/inputbadge/inputBadge.css.ts
packages/components/src/components/common/inputbadge/inputBadge.tsx

https://github.com/axonivy/ui-components/pull/441

XIVY-16748 Input Badges should not wrap > R12

---

packages/components/src/components/editor/browser/browser.stories.tsx
packages/components/src/components/editor/browser/browser.test.tsx
packages/components/src/components/editor/browser/browser.tsx

https://github.com/axonivy/ui-components/pull/422

XIVY-16825 Revert hide single tab in browsers

---

packages/graph/src/data/useGraph.ts

Needed a small adjustment, in order for the initial graph to be rendered correctly ✌️

XIVY-16716 Fix init graphNode-Size

---

packages/graph/src/graph.tsx

- Added new icons to the alignment buttons
- Applied a background color to the graph and reorganized the controls to align with the layout of the process editor

XIVY-16716 Include new graph icons

---

package-lock.json
package.json

https://github.com/axonivy/ui-components/pull/460

Scope all packages > R13.1

---

packages/components/src/components/editor/browser/browser.tsx

This reverts commit 9b3bd5123339a1723f390ab36d310f5fc0ec3a5e.

Revert "XIVY-16846 fix auto focus of browser search"

---

package-lock.json
packages/components/src/components/common/table/data.ts
packages/components/src/components/common/table/header/header.stories.tsx
packages/components/src/components/common/table/row/row.stories.tsx
packages/components/src/components/common/table/table.stories.tsx

https://github.com/axonivy/ui-components/pull/473

Fix table stories > R13.1

---

packages/components/src/components/common/tabs/inscriptionTabData.tsx
packages/components/src/components/common/tabs/tabs.tsx

In the Dataclass-Editor there is a usecase, where there is currently no tab-state (no validation needed), so i change this to optional. What do you think?

XIVY-16852 Make InscriptionTab-State optional

---

packages/components/src/components/common/tabs/inscriptionTabData.tsx
packages/components/src/components/common/tabs/tabs.css.ts
packages/components/src/components/common/tabs/tabs.tsx

Improve UI inscriptoin tabs

---

packages/components/src/components/common/table/hooks/hooks.tsx
packages/components/src/components/common/table/tree/tree.test.tsx

regression of: https://github.com/axonivy/ui-components/pull/505

Fix tree keyboard select

---

packages/components/src/components/common/dialog/dialog.stories.tsx
packages/components/src/components/common/dialog/dialog.test.tsx
packages/components/src/components/common/dialog/dialog.tsx

https://1ivy.atlassian.net/browse/XIVY-16606

XIVY-16606 update basicDialog

---

packages/components/src/components/common/combobox/combobox.css.ts
packages/components/src/components/common/select/select.css.ts

https://github.com/axonivy/ui-components/pull/527

Fix combobox/select on reduce motion

---

.vscode/settings.json
ui-components.code-workspace

https://github.com/axonivy/neo/pull/756

Fix ide lint

---

.vscode/settings.json
ui-components.code-workspace

https://github.com/axonivy/neo/pull/756

Fix ide lint > R12
