axonivy/ui-components

package-lock.json, packages/components/.storybook/preview.tsx, packages/components/package.json, packages/components/tsconfig.json, packages/components/vite.config.ts
We need to use a thridparty utility to generate d.ts files, because typescript does not resolve path aliases.
button.d.ts with tsc:
```ts
import { Flex, type IvyIconProps } from '@/components/common';
```
button.d.ts with vite-plugin-dts:
```ts
import { Flex, IvyIconProps } from '..';
```
'@' is an tsconfic path alias for './src' and this can not be resolved if the package is a dependency in the node_modules folder.
=> Fix library types

packages/components/src/components/common/table/edit/edit.tsx, packages/components/src/components/common/table/table.css.ts, packages/components/src/components/common/table/tree/tree.tsx
Before (first only changes selection of row, second will trigger the collapse/expand):
After fix (expand will no longer trigger the selection):
IMO good behavior and anyway better that the the collapse/expand only trigger on the second click. Maybe you don't want to change the selection with a click on the expand button...
=> Fix expand tree button with select rows

packages/components/src/components/common/table/tree/data.ts, packages/components/src/components/common/table/tree/tree.tsx
On root level, icons are not aligned if some of the entries are collapsible, while they are aligned once the depth is bigger than 0. I think it should look the same in both cases. Thoughts?
Before:
After:
=> XIVY-14003 fix indentation in tree

packages/components/src/components/common/table/tree/tree.css.ts, packages/components/src/components/common/table/tree/tree.tsx, packages/components/src/components/editor/sidebar/header.css.ts
Anaïs said to make all the icons in the variables editor the same size (16px).
I think this should be a global change.
Maybe we should think about streamlining the size of all icons in general to 16px?
=> XIVY-14003 adjust icon sizes

package-lock.json, packages/components/package.json
I have published this branch, see [11.3.2-next.161](https://npmjs-registry.ivyteam.ch/-/web/detail/@axonivy/ui-components/v/11.3.2-next.161). this change would fix the form and config editor issue https://jenkins.ivyteam.io/job/form-editor-client/job/release%252F11.3/64/console
=> set icon peerdep version to *

packages/components/src/components/editor/toolbar/toolbar.css.ts, packages/components/src/components/editor/toolbar/toolbar.stories.tsx, packages/components/src/components/editor/toolbar/toolbar.tsx
I have extended the ToolbarContainer component so that I can easily enable a similar responsive behaviour of the toolbar analogous to the process editor. Now it is not only possible to define that parts above a certain width are no longer displayed, but also the opposite, i.e. that parts above a certain width are only displayed.
=> XIVY-13261 Add minWidth to ToolbarContainer

packages/components/src/components/editor/toolbar/toolbar.css.ts
@ivy-edp 
Always make sure that you catch all cases otherwise something like the following can happen:
=> Fix toolbar container queries

packages/components/src/components/common/table/tree/tree.tsx, packages/components/src/components/editor/browser/browser.stories.tsx, packages/components/src/components/editor/browser/browser.tsx, packages/components/src/components/editor/browser/data.ts
- Support for load more rows lazy
- Add header property for more info or a filter or whatever (imporve story with info what which browser do special)
- Export more Browser types
- Change Browser type `BrowserValue` to `BrowserResult` (with `value` attribute instead of `cursor`)
- Change apply function signature from `(value?: BrowserValue, type?: string) => void` to `(browserName: string, result?: BrowserResult) => void`
- Change applyModifier signature from `(value: string) => BrowserValue` to `(row: Row<BrowserNode>) => BrowserResult`
=> Improve browser component

packages/components/src/utils/table/table.test.ts, packages/components/src/utils/table/table.ts
When calling `deleteFirstSelectedRow` the selection in the table is changed by using some logic. The value of the new selection is usually needed after calling this function. E.g. in the data class editor, after deleting the selected row, the selected field needs to be set to the same selection in the table. Instead of recalculating this value using the same logic, it will be returned from `deleteFirstSelectedRow`.
=> XIVY-12289 return selection after deletion

packages/components/src/components/editor/browser/browser.test.tsx, packages/components/src/components/editor/browser/browser.tsx, packages/components/src/components/editor/browser/data.ts
For the Logic Browser, I have implemented the following two functions:
- Control which row is selectable and which is not
- Define a custom expandedState
This is because the Logic Browser always has the same two root nodes, "Methods" and "Events," and these should always be expanded by default and not selectable.
=> XIVY-13131 Make row not selectable & add custom expandedState

packages/components/src/components/common/button/button.tsx
I want to use the `disabled` property of the buttons in the control to disable this delete button when no annotation is selected:
Any reason to not allow using all the button properties?
I guess otherwise I could hide it entirely or maybe solve this with CSS.
=> XIVY-12288 button props in button group

packages/components/src/index.ts, packages/components/src/utils/useShortcut.test.tsx, packages/components/src/utils/useShortcut.ts
I think this is everything needed here since I can solve the `Enter` case with a form.
I'll answer the question from the [other PR](https://github.com/axonivy/dataclass-editor-client/pull/48) about the following code :
```
const callbackRef = useRef(callback);
useLayoutEffect(() => {
callbackRef.current = callback;
});
```
I got this from [this article](https://www.epicreact.dev/the-latest-ref-pattern-in-react) and in short terms it allows a consumer of this hook to not care about setting up the `callback` function in a `useCallback`. Because we use a reference we do not need to add it to the dependency array of `handleKeyPress`.
=> XIVY-15138 add useShortcut hook

packages/components/src/components/common/table/footer/footer.stories.tsx, packages/components/src/components/common/table/row/row.stories.tsx, packages/components/src/utils/array.ts, packages/components/src/utils/table/table.test.ts, packages/components/src/utils/table/table.ts
I will add tests for the new functions in later PR
Multiselect on ctrl with reorder (Table --> Row --> Multi Select With Reorder): https://jenkins.ivyteam.io/job/ui-components/job/add-multiselectTable-reorder-and-remove/3/artifact/packages/components/storybook-static/index.html?path=/story/common-table-row--multi-select-with-reorder
Multiselect with delete (Table --> Footer --> Remove Multiple): https://jenkins.ivyteam.io/job/ui-components/job/add-multiselectTable-reorder-and-remove/3/artifact/packages/components/storybook-static/index.html?path=/story/common-table-footer--remove-multiple
=> XIVY-15138 Add Multiselect on ctrl and remove/reorder multiselect

packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/editor/browser/browser.stories.tsx, packages/components/src/components/editor/browser/browser.test.tsx, packages/components/src/components/editor/browser/browser.tsx, packages/components/src/components/editor/browser/data.ts
It should be possible to define whether a row is selected by default. This idea originated from the type browser in the DataClass editor; if a type is already present in the input, it should be selected upon the initial opening of the browser. This will help users better understand their current context within the browser.
=> XIVY-15045 Add initial selected row to browser

packages/components/src/components/common/inputbadge/inputBadge.tsx
- only computes tooltipcontent once it is opened to minimize computations
=> XIVY-15526 changes tooltip content to be only computed once hovered

packages/components/src/components/common/select/select.tsx
In the data class editor, I receive undefined for the cardinality of a field with the initial data if it is not set. In this case, the empty item is shown in the select even though nothing seems to be selected. So let's consider undefined when checking whether the empty item is shown by simply checking if the value is truthy.
=> XIVY-15134 treat undefined as empty item in select

packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/common/table/row/row.stories.tsx, packages/components/src/components/common/table/table.css.ts, packages/components/src/components/common/table/table.tsx, packages/components/src/components/common/table/tree/tree.stories.tsx, packages/components/src/components/common/table/tree/tree.tsx, packages/components/src/components/editor/browser/browser.tsx
With this new useTableKeyHandler hook, you are able to add the following keyboard functionality to the table:
- Navigate through rows with arrow up/down
- Expand/close Expandable rows with arrow right/left
- Multiselect rows via Shift + Arrow up/down
- Reorder row(s) via Alt + Arrow up/down
- Add a custom Enter functionality to a row (e.g. browser "Apply")
The hook works perfectly with Readonly-Tables, however with editable tables (especially with Tables that have a SelectCell) it does not behave perfectly (see Table --> Edit --> Keyboard Support).
Within Table --> Row / Table --> Tree / BrowserView --> Dialog Browser are example to test it yourself (https://jenkins.ivyteam.io/job/ui-components/job/make-table-keyboard-friendly/11/artifact/packages/components/storybook-static/index.html?pat …
=> XIVY-15021 Add TableKeyHandler-Hook

packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/common/table/row/row.stories.tsx, packages/components/src/components/common/table/table.css.ts, packages/components/src/components/editor/browser/data.ts
While I integrated keyboard support into the other editors, I noticed a few bugs/improvement points. I have addressed them here:
- When a scrollbar is present, the selected row is now always visible (centered).
- The Tab key only resets the selection if specifically defined in the options.
- The ArrowLeft/Right functionality was reversed.
=> Improve useTableKeyHandler-Hook

packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/common/table/row/row.stories.tsx
To use the structuredClone-Object in the DataClassEditor (see this PR: https://github.com/axonivy/dataclass-editor-client/pull/105), I need to extend the updateOrder-function by passing the clonedObject into the function (to demonstrate this i use the structuredClone-Object in the row story "MultiSelectWithReorder", even though it does not really make sense here).
=> XIVY-13545 Impr. TableKeyHandler to work with structuredClone

package-lock.json, packages/components/package.json, packages/components/src/hooks/hotkey.stories.tsx, packages/components/src/hooks/hotkey.test.tsx, packages/components/src/index.ts, packages/components/src/utils/hotkey.test.tsx, packages/components/src/utils/hotkey.ts, packages/components/src/utils/useShortcut.ts
- Deprecate useShortcut hook
- Add react-hotkeys-hook lib
- Add hotkeyText utility function
master: https://github.com/axonivy/ui-components/pull/218
=> XIVY-15631 Add react-hotkeys-hook, with hotkey helper text function

packages/components/src/components/common/select/select.tsx, packages/components/src/components/common/table/footer/footer.tsx, packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/common/table/row/row.stories.tsx
I hope by adding the possiblity to define a tabindex on SelectCells (all other cells like ComboCell or InputCell do already support this) i can fix the tab bug in edittable with monaco editors
=> XIVY-15861 Add reset row selection on esc and add tabindex to selectcell

packages/components/src/components/common/combobox/combobox.tsx, packages/components/src/components/common/select/select.tsx, packages/components/src/components/common/table/edit/edit.stories.tsx, packages/components/src/components/common/table/edit/edit.test.tsx, packages/components/src/components/common/table/edit/edit.tsx, packages/components/src/components/common/table/footer/footer.tsx, packages/components/src/components/common/table/table.css.ts
I had difficulty seeing which cell was focussed (especially with SelectCell). I have now added the focus-border. Unfortunately I couldn't reuse vars.borders.active here, because for some reason the active border is set to the blue backgroundcolour of the row when rows are selected and so you can't see the border.
=> Border focused editcell

packages/components/src/components/common/table/edit/edit.tsx
I had to extend the selectNextPreviousCell-Function so it also works for editable cells, without a header (for example the MailAttachment-List) or table that have hidden rows (like properties table).
Maybe it would make more sense if i now take this function apart and made it more readable and added additional tests.
=> XIVY-15861 Improve selectNextPreviousCell

.github/renovate.json
Volta is only local dev dependency, ment mainly if you switch to a older branch with an older node version it uses this version.
If we update this, it will cause a new node install for each new node version, so I would keep this manuall for now.
On CI the node version from the docker image is in charge
=> Renovate ignore volta

packages/components/src/components/common/table/hooks/hooks.tsx, packages/components/src/components/common/table/table.tsx
Support virtualized rows when scroll with arrow keys:
instead of:
=> XIVY-16222 Support table key arrow up/down scroll with virtualized rows

packages/components/src/utils/table/table.ts
Export the table utility method `adjustSelectionAfterDeletionOfRow` to be used in the CMS Editor.
This is useful since the data in the CMS Editor is not changed directly but refetched from the back-end.
Because of this, I don't need the additional processing of the data made in `deleteFirstSelectedRow` when deleting a Content Object.
I just want to know what row to select after the fact.
=> XIVY-15943 export `adjustSelectionAfterDeletionOfRow`

packages/graph/src/data/useGraph.ts, packages/graph/src/graph.stories.tsx, packages/graph/src/graph.tsx
The previous approach using defaultViewport didn’t work. This solution does. I also added the option to apply the default zoom when the graph is reordered—either by using the alignment buttons or by double-clicking a node.
=> XIVY-16716 Fix initial zoom level on initial graph rendering

packages/graph/src/data.ts, packages/graph/src/data/getLayoutedElements.ts, packages/graph/src/data/useGraph.ts, packages/graph/src/graph.stories.tsx, packages/graph/src/graph.tsx
Bruno's feedback was that the initially rendered graph didn’t look very polished.
This was because I didn’t know the actual node sizes at the beginning — they only become available afterward. So initially, I set all nodes to a fixed size of 172 x 50. Naturally, this caused some nodes with longer text to be misaligned or poorly positioned.
Now, I'm trying to estimate a more accurate width for each node based on the label length, which works reasonably well. I'm also applying a similar method to calculate the width of the select menu.
=> XIVY-16716 Improve layout of initial rendered graph

packages/components/src/components/editor/browser/browser.test.tsx, packages/components/src/components/editor/browser/browser.tsx
Handling focus in nested dialogs with portaling seems to be complex and does not necessarily work even according to radix.
This ensures that the autofocus of the search input works properly whether it's in a nested dialog or not.
=> XIVY-16846 fix: autofocus in nested dialog browser

package-lock.json, packages/components/src/components/common/dialog/dialog.stories.tsx, packages/components/src/components/common/dialog/dialog.test.tsx, packages/components/src/components/common/dialog/dialog.tsx, packages/components/src/components/editor/browser/browser.stories.tsx, packages/components/src/components/editor/browser/browser.tsx, packages/components/src/hooks/hotkey.ts
- Remove `BasicBrowser` component
Enforces wrong implementation, where to much logic lives outside of the `DialogContent`
- Remove `DialogContent` from `BasicDialogContent`
Enforces wrong implementation, where to much logic lives outside of the `DialogContent`
- `BasicDialogContent` only contains wished structure of a `DialogContent`
- Add `BasicDialogHeader`
If `BasicDialogContent` is not ideal to use
- Add `BasicDialogFooter`
If `BasicDialogContent` is not ideal to use
=> XIVY-16606 Rethink basic browser

packages/components/src/components/common/table/tree/tree.tsx
https://github.com/axonivy/ui-components/pull/423 broke the outline:
Current:
Should be:
=> Fix outline
